apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pg-monitor
  name: pg-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pg-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pg-monitor
    spec:
      containers:
      - image: gcr.io/data-pcf-db/pg-monitor:v0.2
        name: pg-monitor
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Service
metadata:
  name: pg-monitor-entrypoint
spec:
  type: NodePort
  selector:
    pg-monitor: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080
